#!/bin/bash

# notifications.sh - Alert system for critical findings
# Sends real-time notifications to Discord, Telegram, and Email

# Discord webhook URL (set in .env or config)
DISCORD_WEBHOOK="${DISCORD_WEBHOOK:-}"
TELEGRAM_BOT_TOKEN="${TELEGRAM_BOT_TOKEN:-}"
TELEGRAM_CHAT_ID="${TELEGRAM_CHAT_ID:-}"
ALERT_EMAIL="${ALERT_EMAIL:-}"

# Send Discord notification
notify_discord() {
    local severity="$1"
    local title="$2"
    local description="$3"
    local target="${4:-unknown}"

    [ -z "$DISCORD_WEBHOOK" ] && return 0

    # Emoji and color by severity
    local emoji="ℹ️"
    local color="3447003"  # Blue by default

    case "$severity" in
        critical)
            emoji="🚨"
            color="15158332"  # Red
            ;;
        high)
            emoji="⚠️"
            color="15105570"  # Orange
            ;;
        medium)
            emoji="⚡"
            color="15844367"  # Yellow
            ;;
        low)
            emoji="📌"
            color="3066993"   # Green
            ;;
    esac

    local project_id=$(get_current_project)
    local project_name="Unknown"

    if [ -n "$project_id" ]; then
        project_name=$(sqlite3 "$DB_PATH" "SELECT name FROM projects WHERE id = $project_id;" 2>/dev/null || echo "Unknown")
    fi

    local payload=$(cat <<EOF
{
  "embeds": [{
    "title": "$emoji **${severity^^}** - $title",
    "description": "$description",
    "color": $color,
    "fields": [
      {
        "name": "Target",
        "value": "$target",
        "inline": true
      },
      {
        "name": "Project",
        "value": "$project_name",
        "inline": true
      },
      {
        "name": "Timestamp",
        "value": "$(date '+%Y-%m-%d %H:%M:%S')",
        "inline": true
      }
    ],
    "footer": {
      "text": "LeKnight Autopilot v2.1.0"
    }
  }]
}
EOF
)

    curl -s -X POST "$DISCORD_WEBHOOK" \
        -H "Content-Type: application/json" \
        -d "$payload" \
        >/dev/null 2>&1

    log_debug "Discord notification sent: $title"
}

# Send Telegram notification
notify_telegram() {
    local severity="$1"
    local title="$2"
    local description="$3"
    local target="${4:-unknown}"

    [ -z "$TELEGRAM_BOT_TOKEN" ] || [ -z "$TELEGRAM_CHAT_ID" ] && return 0

    local emoji="ℹ️"
    case "$severity" in
        critical) emoji="🚨" ;;
        high) emoji="⚠️" ;;
        medium) emoji="⚡" ;;
        low) emoji="📌" ;;
    esac

    local project_id=$(get_current_project)
    local project_name="Unknown"

    if [ -n "$project_id" ]; then
        project_name=$(sqlite3 "$DB_PATH" "SELECT name FROM projects WHERE id = $project_id;" 2>/dev/null || echo "Unknown")
    fi

    local message="$emoji *LeKnight Alert*

*Severity:* ${severity^^}
*Finding:* $title
*Target:* $target
*Project:* $project_name

$description

_$(date '+%Y-%m-%d %H:%M:%S')_"

    curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
        -d "chat_id=$TELEGRAM_CHAT_ID" \
        -d "text=$message" \
        -d "parse_mode=Markdown" \
        >/dev/null 2>&1

    log_debug "Telegram notification sent: $title"
}

# Send email notification
notify_email() {
    local severity="$1"
    local title="$2"
    local description="$3"
    local target="${4:-unknown}"

    [ -z "$ALERT_EMAIL" ] && return 0

    local subject="[LeKnight] ${severity^^} - $title"

    local project_id=$(get_current_project)
    local project_name="Unknown"

    if [ -n "$project_id" ]; then
        project_name=$(sqlite3 "$DB_PATH" "SELECT name FROM projects WHERE id = $project_id;" 2>/dev/null || echo "Unknown")
    fi

    local body="LeKnight Security Alert

Severity: ${severity^^}
Finding: $title
Target: $target
Project: $project_name

Description:
$description

Timestamp: $(date '+%Y-%m-%d %H:%M:%S')

---
This alert was generated by LeKnight Autopilot v2.1.0"

    # Try mail first, then sendmail
    if command_exists mail; then
        echo "$body" | mail -s "$subject" "$ALERT_EMAIL" 2>/dev/null
    elif command_exists sendmail; then
        {
            echo "To: $ALERT_EMAIL"
            echo "Subject: $subject"
            echo "Content-Type: text/plain; charset=UTF-8"
            echo ""
            echo "$body"
        } | sendmail -t 2>/dev/null
    else
        log_debug "No mail client found, skipping email notification"
        return 1
    fi

    log_debug "Email notification sent to: $ALERT_EMAIL"
}

# Send notification to all configured channels
notify_all() {
    local severity="$1"
    local title="$2"
    local description="$3"
    local target="${4:-unknown}"

    # Only notify for medium and above (unless configured otherwise)
    local min_severity="${NOTIFICATION_MIN_SEVERITY:-medium}"

    case "$min_severity" in
        critical)
            [[ ! "$severity" =~ ^(critical)$ ]] && return 0
            ;;
        high)
            [[ ! "$severity" =~ ^(critical|high)$ ]] && return 0
            ;;
        medium)
            [[ ! "$severity" =~ ^(critical|high|medium)$ ]] && return 0
            ;;
        low)
            [[ ! "$severity" =~ ^(critical|high|medium|low)$ ]] && return 0
            ;;
    esac

    # Send to all configured channels in parallel
    notify_discord "$severity" "$title" "$description" "$target" &
    notify_telegram "$severity" "$title" "$description" "$target" &
    notify_email "$severity" "$title" "$description" "$target" &

    wait
}

# Test notifications
test_notifications() {
    log_section "TESTING NOTIFICATIONS"

    echo -e "${BRIGHT_BLUE}Testing notification channels...${RESET}"
    echo

    # Test Discord
    if [ -n "$DISCORD_WEBHOOK" ]; then
        echo -n "Discord: "
        if notify_discord "info" "Test Notification" "This is a test from LeKnight" "test.example.com"; then
            echo -e "${GREEN}✓ Sent${RESET}"
        else
            echo -e "${RED}✗ Failed${RESET}"
        fi
    else
        echo -e "Discord: ${YELLOW}Not configured (set DISCORD_WEBHOOK)${RESET}"
    fi

    # Test Telegram
    if [ -n "$TELEGRAM_BOT_TOKEN" ] && [ -n "$TELEGRAM_CHAT_ID" ]; then
        echo -n "Telegram: "
        if notify_telegram "info" "Test Notification" "This is a test from LeKnight" "test.example.com"; then
            echo -e "${GREEN}✓ Sent${RESET}"
        else
            echo -e "${RED}✗ Failed${RESET}"
        fi
    else
        echo -e "Telegram: ${YELLOW}Not configured (set TELEGRAM_BOT_TOKEN & TELEGRAM_CHAT_ID)${RESET}"
    fi

    # Test Email
    if [ -n "$ALERT_EMAIL" ]; then
        echo -n "Email: "
        if notify_email "info" "Test Notification" "This is a test from LeKnight" "test.example.com"; then
            echo -e "${GREEN}✓ Sent${RESET}"
        else
            echo -e "${RED}✗ Failed${RESET}"
        fi
    else
        echo -e "Email: ${YELLOW}Not configured (set ALERT_EMAIL)${RESET}"
    fi

    echo
    log_info "Check your configured channels for test messages"
}

# Notification statistics
notification_stats() {
    local project_id=$(get_current_project)

    if [ -z "$project_id" ]; then
        log_error "No project loaded"
        return 1
    fi

    log_section "NOTIFICATION STATISTICS"

    # Count findings by severity
    local critical=$(sqlite3 "$DB_PATH" "SELECT COUNT(*) FROM findings WHERE project_id = $project_id AND severity = 'critical';")
    local high=$(sqlite3 "$DB_PATH" "SELECT COUNT(*) FROM findings WHERE project_id = $project_id AND severity = 'high';")
    local medium=$(sqlite3 "$DB_PATH" "SELECT COUNT(*) FROM findings WHERE project_id = $project_id AND severity = 'medium';")
    local low=$(sqlite3 "$DB_PATH" "SELECT COUNT(*) FROM findings WHERE project_id = $project_id AND severity = 'low';")

    echo -e "${BRIGHT_BLUE}Findings that would trigger notifications:${RESET}"
    echo -e "  🚨 Critical: ${BRIGHT_RED}$critical${RESET}"
    echo -e "  ⚠️  High:     ${RED}$high${RESET}"
    echo -e "  ⚡ Medium:   ${YELLOW}$medium${RESET}"
    echo -e "  📌 Low:      ${BLUE}$low${RESET}"
    echo

    local min_severity="${NOTIFICATION_MIN_SEVERITY:-medium}"
    echo -e "${BRIGHT_BLUE}Current threshold:${RESET} $min_severity"
    echo
}
